name: exercise_detection_app
description: A Flutter application.

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.3.0 <4.0.0"

flutter:
  uses-material-design: true

